---
- name: Configure Fedora workstation
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Import Microsoft GPG key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present
  
    - name: Import RPM Fusion Free GPG key
      ansible.builtin.rpm_key:
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
        state: present

    - name: Import RPM Fusion NonFree GPG key
      ansible.builtin.rpm_key:
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
        state: present

    - name: Add HashiCorp repository
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo

    - name: Add Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add RPM Fusion Free repository
      ansible.builtin.dnf:
        name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
        state: present

    - name: Add RPM Fusion Nonfree repository
      ansible.builtin.dnf:
        name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
        state: present

    - name: Add Docker CE repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/fedora/gpg
